// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	AuthorId  *int       `json:"author_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Example: 1
	Id        *int       `json:"id,omitempty"`
	PostId    *int       `json:"post_id,omitempty"`
	Text      *string    `json:"text,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	// AuthorId Example: 1
	AuthorId int `json:"author_id"`

	// PostId Example: 1
	PostId int `json:"post_id"`

	// Text Example: Отличный пост!
	Text string `json:"text"`
}

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	// AuthorId Example: 1
	AuthorId int `json:"author_id"`

	// Name Example: Мой первый пост
	Name string `json:"name"`

	// Text Example: Содержимое поста
	Text string `json:"text"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// Email Example: ivan@example.com
	Email openapi_types.Email `json:"email"`

	// Name Example: Ivan Petrov
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: resource not found
	Error *string `json:"error,omitempty"`
}

// PostResponse defines model for PostResponse.
type PostResponse struct {
	AuthorId  *int       `json:"author_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id Example: 1
	Id        *int       `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Text      *string    `json:"text,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UpdateCommentRequest defines model for UpdateCommentRequest.
type UpdateCommentRequest struct {
	// AuthorId Example: 1
	AuthorId int `json:"author_id"`

	// PostId Example: 1
	PostId int `json:"post_id"`

	// Text Example: Обновлённый комментарий
	Text string `json:"text"`
}

// UpdatePostRequest defines model for UpdatePostRequest.
type UpdatePostRequest struct {
	// AuthorId Example: 1
	AuthorId int `json:"author_id"`

	// Name Example: Обновлённый пост
	Name string `json:"name"`

	// Text Example: Обновлённое содержимое
	Text string `json:"text"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Email Example: ivan@example.com
	Email openapi_types.Email `json:"email"`

	// Name Example: Ivan Petrov
	Name string `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`

	// Id Example: 1
	Id        *int       `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CreateCommentRequest

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = UpdateCommentRequest

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = CreatePostRequest

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = UpdatePostRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest
